name: Daily Commit

run-name: Commit by 23f2001281@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '13 21 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Append date to file
        run: echo "$(date)" >> daily_commit.txt

      - name: 23f2001281@ds.study.iitm.ac.in
        run: |
          git add daily_commit.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Daily commit"
          git push
